# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake (e.g. the
# bundled lib/tasks/demo.rake) — all are automatically available to rake.
require_relative 'config/application'

Rails.application.load_tasks
